version: "3.8"
services:
 redis:
  image: "redis:alpine"
  environment:
   - ALLOW_EMPTY_PASSWORD=yes
  networks:
   default:
    aliases:
     - redis.service
 db_project:
  image: postgres
  ports:
   - "5050:5432"
  environment:
   - POSTGRES_PORT=5050
   - POSTGRES_DB=project_2cs
   - POSTGRES_USER=project2Cs
   - POSTGRES_PASSWORD=Dr5XKRnFLsesPf73KCjNg
 payment:
  depends_on:
   - db_project
  build:
   context: ./payment
   target: development
  volumes:
   - ./payment:/src
   - /src/node_modules
  command: npm run start:dev
  environment:
   NODE_ENV: development
   DEBUG: src:*
  networks:
   default:
    aliases:
     - payment.api
 pricing_service:
  depends_on:
   - db_project
  build:
   context: ./PricingService
   target: development
  volumes:
   - ./PricingService:/src
   - /src/node_modules
  command: npm run start:dev
  environment:
   NODE_ENV: development
   DEBUG: src:*
  networks:
   default:
    aliases:
     - pricing.api
 subscription_service:
  depends_on:
   - db_project
  build:
   context: ./SubscriptionService
   target: development
  volumes:
   - ./SubscriptionService:/src
   - /src/node_modules
  command: npm run start:dev
  environment:
   NODE_ENV: development
   DEBUG: src:*
  networks:
   default:
    aliases:
     - subscription.api
 signalement_service:
  depends_on:
   - db_project
  build:
   context: ./signals
   target: development
  volumes:
   - ./signals:/src
   - /src/node_modules
  command: npm run start:dev
  environment:
   NODE_ENV: development
   DEBUG: src:*
  networks:
   default:
    aliases:
     - signalement.api
 create-facture:
  depends_on:
   - db_project
  build:
   context: ./create-facture
   target: development
  volumes:
   - ./create-facture:/src
   - /src/node_modules
  command: npm run start:dev
  environment:
   NODE_ENV: development
   DEBUG: src:*
  networks:
   default:
    aliases:
     - facture.api
 template:
  depends_on:
   - db_project
  build:
   context: ./template
   target: development
  volumes:
   - ./template:/src
   - /src/node_modules
  command: npm run start:dev
  environment:
   NODE_ENV: development
   DEBUG: src:*
  networks:
   default:
    aliases:
     - vehicle.api
 services_getwaye:
  build: ./services-getwaye
  volumes:
   - ./services-getwaye:/app
   - /app/node_modules
  command: npm start
  ports:
   - "7000:7000"
  environment:
   NODE_ENV: development
   LOG_LEVEL: debug
 promo_service:
  depends_on:
   - db_project
  build:
   context: ./PromoCodeService
   target: development
  volumes:
   - ./PromoCodeService:/src
   - /src/node_modules
  command: npm run start:dev
  environment:
   NODE_ENV: development
   DEBUG: src:*
  networks:
   default:
    aliases:
     - promotion.api
 rental_service:
  depends_on:
    - db_project
  build:
    context: ./Rental
    target: development
  volumes:
    - ./Rental:/src
    - /src/node_modules
  command: npm run start:dev
  environment:
    NODE_ENV: development
    DEBUG: src:*
  networks:
    default:
     aliases:
      - rentals.api
 auth_service:
  depends_on:
   - db_project
  build:
   context: ./Authentication
   target: development
  volumes:
   - ./Authentication:/src
   - /src/node_modules
  command: npm run start:dev
  environment:
   NODE_ENV: development
   DEBUG: src:*
  networks:
   default:
    aliases:
     - auth.api
 rentalbyuser_service:
  depends_on:
   - db_project
  build:
   context: ./rentalByUser
   target: development
  volumes:
   - ./rentalByUser:/src
   - /src/node_modules
  command: npm run start:dev
  environment:
   NODE_ENV: development
   DEBUG: src:*
  networks:
   default:
    aliases:
     - rentalUser.api
 borne_services:
  depends_on:
   - db_project
  build:
   context: ./borne-vehicule
   target: development
  volumes:
   - ./borne-vehicule:/src
   - /src/node_modules
  command: npm run start:dev
  environment:
   NODE_ENV: development
   DEBUG: src:*
  networks:
   default:
    aliases:
     - bornes.api
 association:
  depends_on:
   - db_project
  build:
   context: ./association
   target: development
  volumes:
   - ./association:/src
   - /src/node_modules
  ports:
   - "7001:8000"
  command: npm run start:dev
  environment:
   NODE_ENV: development
   DEBUG: src:*
  networks:
   default:
    aliases:
     - association.api
 auto_signal:
  depends_on:
   - db_project
  build:
   context: ./auto_signal
   target: development
  volumes:
   - ./auto_signal:/src
   - /src/node_modules
  command: npm run start:dev
  environment:
   NODE_ENV: development
   DEBUG: src:*
  networks:
   default:
    aliases:
     - signal.api
 users_service:
  depends_on:
   - db_project
  build:
   context: ./user
   target: development
  volumes:
   - ./user:/src
   - /src/node_modules
  command: npm run start:dev
  environment:
   NODE_ENV: development
   DEBUG: src:*
  networks:
   default:
    aliases:
     - users.api
 tdm_service:
  depends_on:
   - db_project
  build:
   context: ./tdm
   target: development
  ports:
    - "5600:3000"
  volumes:
   - ./tdm:/src
   - /src/node_modules
  command: npm run dev
  environment:
   NODE_ENV: development
   DEBUG: src:*
