name: Wb service jta CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
  
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_SERVER }}
        username: ${{ secrets.SSH_USERNAME_SERVER }}
        key: ${{ secrets.SSH_KEY_SERVER }}
        port: ${{ secrets.SSH_PORT_SERVER }}
        script: |
          cd /home/service
          git add .
          git commit -m "local change"
          git pull origin main
